import 'package:e_voucher/Classes/vousher_log.dart';

class vouchers{
 int? VOUCHERID;
  int? ACTUALVALUE;
  int? NAMEDVALUE;
  int? USEDVALUE;
  int? VOUCHERTYPEIDFK;
  int? VOUCHERSTATUSIDFK;
   var ASSIGNDATE;
   var USAGEDATE;
   var RECEIVERIDFK;
   var STOREBRANCHIDFK;
   var PROMOCODE;
   var HASHEDVALUE;
   var RELATEDVOUCHERIDFK;
   var OFFERIDFK;
   int? CREATEUSERIDFK;
   String? CREATEDATE;
   var MODUSERIDFK;
   var MODDATE;
   String? ACTIVE;
   var PAYMENTTYPE;
   var TRANSACTIONTYPEIDFK;
   var OFFER;
   var RECIEVERUSER;
   var STOREBRANCH;
   var TRANSACTIONTYPE;
   var VOUCHERSTATUS;
   var VOUCHERTYPE;
 List<VOUCHERLog>? VOUCHERLOG;

  vouchers({this.ACTIVE,this.VOUCHERID,
  this.ACTUALVALUE ,
   this.ASSIGNDATE,
  this.HASHEDVALUE,
  this.NAMEDVALUE,
  this.OFFER,
  this.OFFERIDFK,
  this.PAYMENTTYPE,
  this.PROMOCODE,
  this.RECEIVERIDFK,
  this.RECIEVERUSER,
  this.RELATEDVOUCHERIDFK,
 this.STOREBRANCH,
 this.TRANSACTIONTYPE,
 this.TRANSACTIONTYPEIDFK,
  this.USAGEDATE,
  this.USEDVALUE,
  this.VOUCHERLOG,
  this.VOUCHERSTATUS,
 this.VOUCHERSTATUSIDFK,
 this.VOUCHERTYPE,
  this.VOUCHERTYPEIDFK,
  this.STOREBRANCHIDFK,
  this.CREATEUSERIDFK,
  this.CREATEDATE,
  this.MODUSERIDFK,
  this.MODDATE,
  });
  factory vouchers.fromJson(Map<String,dynamic> json){

    vouchers V = vouchers();
    V.VOUCHERTYPE = json['VOUCHERTYPE'];
    V.VOUCHERID=json['VOUCHERID'];
    V.ACTIVE=json['ACTIVE'];
    V.ASSIGNDATE=json['ASSIGNDATE'];
    V.HASHEDVALUE=json['HASHEDVALUE'];
    V.NAMEDVALUE=json['NAMEDVALUE'];
    V.OFFER=json['OFFER'];
    V.OFFERIDFK=json['OFFERIDFK'];
    V.PAYMENTTYPE=json['PAYMENTTYPE'];
    V.PROMOCODE=json['PROMOCODE'];
    V.RECEIVERIDFK=json['RECEIVERIDFK'];
    V.RECIEVERUSER=json['RECIEVERUSER'];
    V.RELATEDVOUCHERIDFK=json['RELATEDVOUCHERIDFK'];
    V.STOREBRANCH=json['STOREBRANCH'];
    V.TRANSACTIONTYPE=json['TRANSACTIONTYPE'];
    V.TRANSACTIONTYPEIDFK=json['TRANSACTIONTYPEIDFK'];
    V.USAGEDATE=json['USAGEDATE'];
    V.USEDVALUE=json['USEDVALUE'];
    V.VOUCHERSTATUS=json['VOUCHERSTATUS'];
    V.VOUCHERSTATUSIDFK=json['VOUCHERSTATUSIDFK'];
    V.VOUCHERTYPE=json['VOUCHERTYPE'];
    V.VOUCHERTYPEIDFK=json['VOUCHERTYPEIDFK'];
    V.STOREBRANCHIDFK=json['STOREBRANCHIDFK'];
    V.CREATEUSERIDFK=json['CREATEUSERIDFK'];
    V.CREATEDATE=json['CREATEDATE'];
    V.MODUSERIDFK=json['MODUSERIDFK'];
    V.MODDATE=json['MODDATE'];
  return V;
  }


  }



